.PHONY: all

PROTO_ROOT  := proto

# Go 输出目录
PB_GO := ./go
# Dart 输出目录
PB_DART := dart/lib/src
DART_EXPORT_DIR := dart/lib

# protoc 命令
PROTOC := protoc

# 查找所有 proto 文件
PROTO_FILES := $(shell find $(PROTO_ROOT) -name "*.proto")
# 相对 proto 根目录的路径（用于保持输出目录结构）
PROTO_FILES_REL := $(patsubst $(PROTO_ROOT)/%,%,$(PROTO_FILES))

.PHONY: all go dart clean

# 默认全部生成
all: go dart

# -----------------------
# 生成 Go pb 文件
# -----------------------
go: clean $(PROTO_FILES)
	mkdir -p $(PB_GO);
	@echo "Generating Go pb files..."
	@for f in $(PROTO_FILES_REL); do \
		$(PROTOC) -I $(PROTO_ROOT) \
			--go_out=$(PB_GO) --go_opt=paths=source_relative \
			--go-grpc_out=$(PB_GO) --go-grpc_opt=paths=source_relative \
			$$f; \
		echo "Generated $$f -> $(PB_GO)"; \
	done
	@echo "Generating Go mod files..."
	go mod tidy -go=1.25 -compat=1.25

# -----------------------
# 生成 Dart pb 文件
# -----------------------
dart: $(PROTO_FILES)
	@echo "Generating Dart pb files..."
	mkdir -p $(PB_DART);
	@for f in $(PROTO_FILES_REL); do \
		$(PROTOC) -I $(PROTO_ROOT) \
			--dart_out=grpc:$(PB_DART) \
			$$f; \
		echo "Generated $$f -> $(PB_DART)"; \
	done
	# export all generated pb.dart files to proto.dart
	@echo "Exporting all Dart pb files to proto.dart..."
	@{ \
		echo "// Code generated by Makefile. DO NOT EDIT."; \
		echo "library proto;"; \
		find $(PB_DART) -type f -name "*.pb.dart" | LC_ALL=C sort | \
			sed "s#^$(DART_EXPORT_DIR)/##" | \
			while IFS= read -r f; do printf "export '%s';\n" "$$f"; done; \
	} > $(DART_EXPORT_DIR)/proto.dart

# -----------------------
# 清理生成文件
# -----------------------
clean:
	@if [ -d $(PB_GO) ]; then find $(PB_GO) -type f \( -name "*.pb.go" -o -name "*_grpc.pb.go" \) -delete; fi
	@if [ -d $(PB_DART) ]; then find $(PB_DART) -type f -name "*.pb*.dart" -delete; fi
