syntax = "proto3";
import "user.proto";

package zoogle;

option go_package = "asia.zoogle/zoogle-server/proto";

message Post {
  int64 id = 1;
  int64 author_id = 2;

  string content = 3;
  repeated  string  images = 4;
  repeated  string  tags = 5;
  int64 created_at = 6;
  int64 updated_at = 7;
}

message PostDetail {
  Post post = 1;
  User author = 2;
  int32  likes = 3;
  bool liked_by_current_user = 4;
}

service PostService {
  rpc CreatePost(CreatePostRequest) returns (CreatePostResponse);
  rpc GetPost(GetPostRequest) returns (GetPostResponse);
  rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse);
  rpc DeletePost(DeletePostRequest) returns (DeletePostResponse);

  rpc GetPostPageable(GetPostPageableRequest) returns (GetPostPageableResponse);

  rpc GetPostByUserId(GetPostByUserIdRequest) returns (GetPostByUserIdResponse);

  rpc LikePost(LikePostRequest) returns (LikePostResponse);
  rpc GetPostDetail(GetPostRequest) returns (PostDetail);
}

message  CreatePostRequest{
  string content = 1;
  repeated string images = 2;
  repeated  string  tags = 3;
}
message CreatePostResponse {
  Post post = 1;
}

message GetPostRequest{
  int64 id = 1;
}
message GetPostResponse{
  Post post = 1;
}
message UpdatePostRequest{
  int64 id = 1;
  string content = 2;
  repeated string images = 3;
  repeated  string  tags = 4;
}
message UpdatePostResponse{
  Post post = 1;
}

message DeletePostRequest{
  repeated int64 ids = 1;
}

message DeletePostResponse{
  bool success = 1;
}

message GetPostPageableRequest{
  int32 page = 1;
  int32 page_size = 2;
  optional  string  q = 3;
}
message GetPostPageableResponse{
  repeated Post posts = 1;
  int32 page = 2;
  int32 page_size = 3;
  int32 total = 4;
}

message GetPostByUserIdRequest{
  int64 user_id = 1;
  int32 page = 2;
  int32 page_size = 3;
}

message  GetPostByUserIdResponse{
  repeated Post posts = 1;
  int32 page = 2;
  int32 page_size = 3;
  int32 total = 4;
}

message  LikePostRequest{
  int64 post_id = 1;
  bool like = 2;
}

message  LikePostResponse{
}