syntax = 'proto3';
package zoogle;

option go_package = "asia.zoogle/zoogle-server/proto";

import "empty.proto";


message  User {
  uint64 id = 1;
  string name = 2;
  string phone = 3;
  string avatar = 4;
}


// service
service UserService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Register(RegisterRequest) returns (User);
  rpc GetUser (GetUserRequest) returns (User);
  rpc UpdateUser(UpdateUserRequest) returns (User);
  rpc Self(zoogle.base.Empty) returns (User);
}

message GetUserRequest {
  uint64 id= 1;
}

message UpdateUserRequest{
  uint64 id = 1;
  optional string name = 2;
  optional string avatar = 3;
  optional string phone = 4;
  optional string password = 5;
}

enum LoginMethod {
  PASSWORD = 0;
  SMS_CODE = 1;
}

message LoginRequest {
  // 电话号码
  string phone = 1;
  // 密码
  string password = 2;
  // 可选 设备类型
  optional  int32 device_id = 3;
  // sms code
  optional string sms_code=4;
  // 登陆方式
  LoginMethod method = 5;
}
message LoginResponse{
  User user = 1;
  string token = 2;
}
message RegisterRequest{
  string name = 1;
  string phone = 2;
  optional string avatar = 3;
  optional string smsCode=4;
  optional string password = 5;
  LoginMethod method = 6;
}