// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: im/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Text  MessageType = 0
	MessageType_Image MessageType = 1
	MessageType_Video MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Text",
		1: "Image",
		2: "Video",
	}
	MessageType_value = map[string]int32{
		"Text":  0,
		"Image": 1,
		"Video": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_im_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{0}
}

type ChatClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatClientMessage_Auth
	//	*ChatClientMessage_SendMessage
	//	*ChatClientMessage_AckMessage
	//	*ChatClientMessage_Heartbeat
	Payload       isChatClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatClientMessage) Reset() {
	*x = ChatClientMessage{}
	mi := &file_im_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatClientMessage) ProtoMessage() {}

func (x *ChatClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatClientMessage.ProtoReflect.Descriptor instead.
func (*ChatClientMessage) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatClientMessage) GetPayload() isChatClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatClientMessage) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Payload.(*ChatClientMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ChatClientMessage) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatClientMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ChatClientMessage) GetAckMessage() *AckMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatClientMessage_AckMessage); ok {
			return x.AckMessage
		}
	}
	return nil
}

func (x *ChatClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ChatClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isChatClientMessage_Payload interface {
	isChatClientMessage_Payload()
}

type ChatClientMessage_Auth struct {
	Auth *Auth `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ChatClientMessage_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ChatClientMessage_AckMessage struct {
	AckMessage *AckMessage `protobuf:"bytes,3,opt,name=ack_message,json=ackMessage,proto3,oneof"`
}

type ChatClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ChatClientMessage_Auth) isChatClientMessage_Payload() {}

func (*ChatClientMessage_SendMessage) isChatClientMessage_Payload() {}

func (*ChatClientMessage_AckMessage) isChatClientMessage_Payload() {}

func (*ChatClientMessage_Heartbeat) isChatClientMessage_Payload() {}

type ChatServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatServerEvent_NewMessage
	//	*ChatServerEvent_MessageAck
	//	*ChatServerEvent_PresenceUpdate
	//	*ChatServerEvent_SystemEvent
	Payload       isChatServerEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatServerEvent) Reset() {
	*x = ChatServerEvent{}
	mi := &file_im_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatServerEvent) ProtoMessage() {}

func (x *ChatServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatServerEvent.ProtoReflect.Descriptor instead.
func (*ChatServerEvent) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatServerEvent) GetPayload() isChatServerEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatServerEvent) GetNewMessage() *NewMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatServerEvent_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *ChatServerEvent) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*ChatServerEvent_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *ChatServerEvent) GetPresenceUpdate() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ChatServerEvent_PresenceUpdate); ok {
			return x.PresenceUpdate
		}
	}
	return nil
}

func (x *ChatServerEvent) GetSystemEvent() *SystemEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatServerEvent_SystemEvent); ok {
			return x.SystemEvent
		}
	}
	return nil
}

type isChatServerEvent_Payload interface {
	isChatServerEvent_Payload()
}

type ChatServerEvent_NewMessage struct {
	NewMessage *NewMessage `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type ChatServerEvent_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,2,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type ChatServerEvent_PresenceUpdate struct {
	PresenceUpdate *PresenceUpdate `protobuf:"bytes,3,opt,name=presence_update,json=presenceUpdate,proto3,oneof"`
}

type ChatServerEvent_SystemEvent struct {
	SystemEvent *SystemEvent `protobuf:"bytes,4,opt,name=system_event,json=systemEvent,proto3,oneof"`
}

func (*ChatServerEvent_NewMessage) isChatServerEvent_Payload() {}

func (*ChatServerEvent_MessageAck) isChatServerEvent_Payload() {}

func (*ChatServerEvent_PresenceUpdate) isChatServerEvent_Payload() {}

func (*ChatServerEvent_SystemEvent) isChatServerEvent_Payload() {}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_im_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_im_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{3}
}

type SendMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId    string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=chat.v1.MessageType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_im_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessage) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Text
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // delivered, read
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_im_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{5}
}

func (x *AckMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NewMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,6,opt,name=type,proto3,enum=chat.v1.MessageType" json:"type,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_im_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{6}
}

func (x *NewMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *NewMessage) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *NewMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NewMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Text
}

func (x *NewMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_im_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MessageAck) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // online, offline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_im_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PresenceUpdate) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PresenceUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SystemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemEvent) Reset() {
	*x = SystemEvent{}
	mi := &file_im_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEvent) ProtoMessage() {}

func (x *SystemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEvent.ProtoReflect.Descriptor instead.
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SystemEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SystemEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_im_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ListConversationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConversationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_im_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IsGroup       bool                   `protobuf:"varint,3,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Members       []*Member              `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_im_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{12}
}

func (x *Conversation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Conversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Conversation) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_im_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_im_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_im_chat_proto_rawDescGZIP(), []int{13}
}

func (x *Member) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_im_chat_proto protoreflect.FileDescriptor

const file_im_chat_proto_rawDesc = "" +
	"\n" +
	"\rim/chat.proto\x12\achat.v1\"\xea\x01\n" +
	"\x11ChatClientMessage\x12#\n" +
	"\x04auth\x18\x01 \x01(\v2\r.chat.v1.AuthH\x00R\x04auth\x129\n" +
	"\fsend_message\x18\x02 \x01(\v2\x14.chat.v1.SendMessageH\x00R\vsendMessage\x126\n" +
	"\vack_message\x18\x03 \x01(\v2\x13.chat.v1.AckMessageH\x00R\n" +
	"ackMessage\x122\n" +
	"\theartbeat\x18\x04 \x01(\v2\x12.chat.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x8b\x02\n" +
	"\x0fChatServerEvent\x126\n" +
	"\vnew_message\x18\x01 \x01(\v2\x13.chat.v1.NewMessageH\x00R\n" +
	"newMessage\x126\n" +
	"\vmessage_ack\x18\x02 \x01(\v2\x13.chat.v1.MessageAckH\x00R\n" +
	"messageAck\x12B\n" +
	"\x0fpresence_update\x18\x03 \x01(\v2\x17.chat.v1.PresenceUpdateH\x00R\x0epresenceUpdate\x129\n" +
	"\fsystem_event\x18\x04 \x01(\v2\x14.chat.v1.SystemEventH\x00R\vsystemEventB\t\n" +
	"\apayload\"\x1c\n" +
	"\x04Auth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\v\n" +
	"\tHeartbeat\"\x9e\x01\n" +
	"\vSendMessage\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.chat.v1.MessageTypeR\x04type\"C\n" +
	"\n" +
	"AckMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xe9\x01\n" +
	"\n" +
	"NewMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12(\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.chat.v1.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"C\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"A\n" +
	"\x0ePresenceUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\vSystemEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x18ListConversationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x80\x01\n" +
	"\x19ListConversationsResponse\x12;\n" +
	"\rconversations\x18\x01 \x03(\v2\x15.chat.v1.ConversationR\rconversations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x99\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bis_group\x18\x03 \x01(\bR\aisGroup\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12)\n" +
	"\amembers\x18\x06 \x03(\v2\x0f.chat.v1.MemberR\amembers\"T\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl*-\n" +
	"\vMessageType\x12\b\n" +
	"\x04Text\x10\x00\x12\t\n" +
	"\x05Image\x10\x01\x12\t\n" +
	"\x05Video\x10\x022\xb1\x01\n" +
	"\vChatService\x12F\n" +
	"\n" +
	"ChatStream\x12\x1a.chat.v1.ChatClientMessage\x1a\x18.chat.v1.ChatServerEvent(\x010\x01\x12Z\n" +
	"\x11ListConversations\x12!.chat.v1.ListConversationsRequest\x1a\".chat.v1.ListConversationsResponseB+Z)github.com/ren/zoogle-im/proto/gen;chatv1b\x06proto3"

var (
	file_im_chat_proto_rawDescOnce sync.Once
	file_im_chat_proto_rawDescData []byte
)

func file_im_chat_proto_rawDescGZIP() []byte {
	file_im_chat_proto_rawDescOnce.Do(func() {
		file_im_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_chat_proto_rawDesc), len(file_im_chat_proto_rawDesc)))
	})
	return file_im_chat_proto_rawDescData
}

var file_im_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_im_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_im_chat_proto_goTypes = []any{
	(MessageType)(0),                  // 0: chat.v1.MessageType
	(*ChatClientMessage)(nil),         // 1: chat.v1.ChatClientMessage
	(*ChatServerEvent)(nil),           // 2: chat.v1.ChatServerEvent
	(*Auth)(nil),                      // 3: chat.v1.Auth
	(*Heartbeat)(nil),                 // 4: chat.v1.Heartbeat
	(*SendMessage)(nil),               // 5: chat.v1.SendMessage
	(*AckMessage)(nil),                // 6: chat.v1.AckMessage
	(*NewMessage)(nil),                // 7: chat.v1.NewMessage
	(*MessageAck)(nil),                // 8: chat.v1.MessageAck
	(*PresenceUpdate)(nil),            // 9: chat.v1.PresenceUpdate
	(*SystemEvent)(nil),               // 10: chat.v1.SystemEvent
	(*ListConversationsRequest)(nil),  // 11: chat.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 12: chat.v1.ListConversationsResponse
	(*Conversation)(nil),              // 13: chat.v1.Conversation
	(*Member)(nil),                    // 14: chat.v1.Member
}
var file_im_chat_proto_depIdxs = []int32{
	3,  // 0: chat.v1.ChatClientMessage.auth:type_name -> chat.v1.Auth
	5,  // 1: chat.v1.ChatClientMessage.send_message:type_name -> chat.v1.SendMessage
	6,  // 2: chat.v1.ChatClientMessage.ack_message:type_name -> chat.v1.AckMessage
	4,  // 3: chat.v1.ChatClientMessage.heartbeat:type_name -> chat.v1.Heartbeat
	7,  // 4: chat.v1.ChatServerEvent.new_message:type_name -> chat.v1.NewMessage
	8,  // 5: chat.v1.ChatServerEvent.message_ack:type_name -> chat.v1.MessageAck
	9,  // 6: chat.v1.ChatServerEvent.presence_update:type_name -> chat.v1.PresenceUpdate
	10, // 7: chat.v1.ChatServerEvent.system_event:type_name -> chat.v1.SystemEvent
	0,  // 8: chat.v1.SendMessage.type:type_name -> chat.v1.MessageType
	0,  // 9: chat.v1.NewMessage.type:type_name -> chat.v1.MessageType
	13, // 10: chat.v1.ListConversationsResponse.conversations:type_name -> chat.v1.Conversation
	14, // 11: chat.v1.Conversation.members:type_name -> chat.v1.Member
	1,  // 12: chat.v1.ChatService.ChatStream:input_type -> chat.v1.ChatClientMessage
	11, // 13: chat.v1.ChatService.ListConversations:input_type -> chat.v1.ListConversationsRequest
	2,  // 14: chat.v1.ChatService.ChatStream:output_type -> chat.v1.ChatServerEvent
	12, // 15: chat.v1.ChatService.ListConversations:output_type -> chat.v1.ListConversationsResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_im_chat_proto_init() }
func file_im_chat_proto_init() {
	if File_im_chat_proto != nil {
		return
	}
	file_im_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatClientMessage_Auth)(nil),
		(*ChatClientMessage_SendMessage)(nil),
		(*ChatClientMessage_AckMessage)(nil),
		(*ChatClientMessage_Heartbeat)(nil),
	}
	file_im_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatServerEvent_NewMessage)(nil),
		(*ChatServerEvent_MessageAck)(nil),
		(*ChatServerEvent_PresenceUpdate)(nil),
		(*ChatServerEvent_SystemEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_chat_proto_rawDesc), len(file_im_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_chat_proto_goTypes,
		DependencyIndexes: file_im_chat_proto_depIdxs,
		EnumInfos:         file_im_chat_proto_enumTypes,
		MessageInfos:      file_im_chat_proto_msgTypes,
	}.Build()
	File_im_chat_proto = out.File
	file_im_chat_proto_goTypes = nil
	file_im_chat_proto_depIdxs = nil
}
