syntax = "proto3";

package chat.v1;

option go_package = "github.com/ren/zoogle-im/proto/gen;chatv1";

service ChatService {
  rpc ChatStream(stream ChatClientMessage) returns (stream ChatServerEvent);
  rpc CreateConversation(CreateConversationRequest) returns (CreateConversationResponse);
  rpc ListConversations(ListConversationsRequest) returns (ListConversationsResponse);
}

message ChatClientMessage {
  oneof payload {
    Auth         auth = 1;
    SendMessage  send_message = 2;
    AckMessage   ack_message = 3;
    Heartbeat    heartbeat = 4;
  }
}

message ChatServerEvent {
  oneof payload {
    NewMessage      new_message = 1;
    MessageAck      message_ack = 2;
    PresenceUpdate  presence_update = 3;
    SystemEvent     system_event = 4;
  }
}

message Auth {
  string token = 1;
  int64 last_received_at = 2; // timestamp of the last received message, for resuming
}

message Heartbeat {}



enum  MessageType{
  Text = 0;
  Image = 1;
  Video = 2;
}
message SendMessage {
  string client_msg_id = 1;
  int64 conversation_id = 2;
  string content = 3;
  MessageType type = 4;
}

message AckMessage {
  string message_id = 1;
  string status = 2; // delivered, read
}

message NewMessage {
  int64 id = 1;
  string client_msg_id = 2;
  int64 conversation_id = 3;
  int64 sender_id = 4;
  string content = 5;
  MessageType type = 6;
  int64  created_at = 7;
}
enum MessageAckStatus {
  DELIVERED = 0;
  READ = 1;
}

message MessageAck {
  int64 message_id = 1;
  string client_id = 2;
  MessageAckStatus status = 3;
}

message PresenceUpdate {
  int64 user_id = 1;
  string status = 2; // online, offline
}

message SystemEvent {
  string code = 1;
  string message = 2;
}

message ListConversationsRequest {
  int64 page_size = 1;
  int64 page = 2;
  string  keywords = 3;
  optional  bool is_group = 4;
}

message ListConversationsResponse {
  repeated Conversation conversations = 1;
  int64 total = 3;
  optional  bool has_next = 2;
}

message Conversation {
  int64 id = 1;
  string title = 2;
  bool   is_group = 3;
  int64  updated_at = 4;
  repeated  int64 members = 6;
}

message  CreateConversationRequest{
  string title = 1;
  bool   is_group = 2;
  repeated int64 member_ids = 3;
}

message CreateConversationResponse {
  Conversation conversation = 1;
}