name: version

permissions:
  contents: write       # repo 文件操作
  issues: write         # issue/comment 权限
  pull-requests: write  # PR 权限

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
